services:

  # Must run in root mode to access USB devices
  coral:
    container_name: coral
    image: ghcr.io/tmarquard1/framegate:latest
    build:
      context: ./
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/arm64
        cache-from:
          - type=registry,ref=ghcr.io/tmarquard1/framegate:cache
        cache-to:
          - mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=ghcr.io/tmarquard1/framegate:cache

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/vchiq:/dev/vchiq
    init: true
