services:

  # Must run in root mode to access USB devices
  coral:
    container_name: coral
    image: ghcr.io/tmarquard1/framegate:latest
    build:
      context: ./
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/arm64
        cache-from:
          - type=registry,ref=ghcr.io/tmarquard1/framegate:cache
        cache-to:
          - mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=ghcr.io/tmarquard1/framegate:cache

    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/vchiq:/dev/vchiq
    volumes:
      # - /usr/lib/aarch64-linux-gnu/rpicam_app.so.1.5.0:/usr/lib/aarch64-linux-gnu/rpicam_app.so.1.5.0
      # - /usr/lib/aarch64-linux-gnu/libcamera.so.0.3:/usr/lib/aarch64-linux-gnu/libcamera.so.0.3
      # - /usr/lib/aarch64-linux-gnu/libboost_program_options.so.1.74.0:/usr/lib/aarch64-linux-gnu/libboost_program_options.so.1.74.0
      - /usr/bin/rpicam-still:/usr/bin/rpicam-still
      - /usr/lib/aarch64-linux-gnu:/usr/host-libs
      # - /run/udev:/run/udev:ro
    # environment:
    # - LD_LIBRARY_PATH=/usr/host-libs:/usr/host-libs/pulseaudio:$LD_LIBRARY_PATH
    #   - LD_LIBRARY_PATH=/usr/rpi/
    init: true

    # put /Users/tmarquard/Documents/Personal/CSU\ Graduate\ School/FrameGate/docker-compose.yml /home/tmarquard/Documents/FrameGate/docker-compose.yml
